/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface OrderConfirmation {
  'id' : bigint,
  'totalINR' : bigint,
  'upiRef' : string,
  'timestamp' : bigint,
  'buyer' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'unitPriceINR' : bigint,
  'quantity' : bigint,
  'product' : string,
}
export interface OrderPayload {
  'upiRef' : string,
  'buyer' : string,
  'items' : Array<OrderItem>,
}
export interface UserProfile {
  'name' : string,
  'minecraftUsername' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[OrderPayload], bigint>,
  'getAllOrders' : ActorMethod<[], Array<OrderConfirmation>>,
  'getBestSellingProducts' : ActorMethod<[], Array<[string, bigint]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getItemsByProduct' : ActorMethod<[string], Array<OrderItem>>,
  'getOrderById' : ActorMethod<[bigint], [] | [OrderConfirmation]>,
  'getOrdersByBuyer' : ActorMethod<[string], Array<OrderConfirmation>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];